### ISSUE TITLE
Latest provider version `1.21.0` fails with terraform `1.0.9`

### ISSUE THREAD

**Issue by daconstenla** [Myra-Security-GmbH/terraform-provider-myrasec#31]
When trying to perform any terraform operation like `plan` or `apply` terraform execution fails claiming the plugin has crashed: `Error: The terraform-provider-myrasec_v1.21.0 plugin crashed!`.

- terraform code only manipulates myracloud's resources.
- previous versions applied this code without problems (no updates to the code have been performed)

**Context versions**

terraform version: `1.0.9`
Myra-Security-GmbH/myrasec version: `1.21.0` ([link to the release](https://github.com/Myra-Security-GmbH/terraform-provider-myrasec/releases/tag/v1.21.0))
OS: macos 12.1

**Error log**

```terraform
TF_LOG_PROVIDER=debug terraform plan
2022-02-15T12:51:16.096+0100 [INFO]  provider: configuring client automatic mTLS
2022-02-15T12:51:16.142+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 args=[.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0]
2022-02-15T12:51:16.150+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 pid=10432
2022-02-15T12:51:16.150+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0
2022-02-15T12:51:16.990+0100 [INFO]  provider.terraform-provider-myrasec_v1.21.0: configuring server automatic mTLS: timestamp=2022-02-15T12:51:16.989+0100
2022-02-15T12:51:16.998+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: plugin address: address=/var/folders/ss/fk1dkdp97sj444ldlchfn3fw0000gq/T/plugin3050056821 network=unix timestamp=2022-02-15T12:51:16.998+0100
2022-02-15T12:51:16.999+0100 [DEBUG] provider: using plugin: version=5
2022-02-15T12:51:17.046+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-02-15T12:51:17.047+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 pid=10432
2022-02-15T12:51:17.047+0100 [DEBUG] provider: plugin exited
2022-02-15T12:51:17.064+0100 [INFO]  provider: configuring client automatic mTLS
2022-02-15T12:51:17.100+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 args=[.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0]
2022-02-15T12:51:17.108+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 pid=10434
2022-02-15T12:51:17.108+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0
2022-02-15T12:51:17.124+0100 [INFO]  provider.terraform-provider-myrasec_v1.21.0: configuring server automatic mTLS: timestamp=2022-02-15T12:51:17.123+0100
2022-02-15T12:51:17.132+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: plugin address: address=/var/folders/ss/fk1dkdp97sj444ldlchfn3fw0000gq/T/plugin2786673231 network=unix timestamp=2022-02-15T12:51:17.132+0100
2022-02-15T12:51:17.132+0100 [DEBUG] provider: using plugin: version=5
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: PANIC: can't convert (schema.SchemaDefaultFunc)(0x144ec60) to cty.Value
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: 
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: goroutine 42 [running]:
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/terraform-plugin-sdk/v2/internal/configs/hcl2shim.HCL2ValueFromConfigValue({0x16f1240, 0xc0002d8180})
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/configs/hcl2shim/values.go:228 +0x3ce
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PrepareProviderConfig.func1({0xc000399270, 0xc000036429, 0x0}, {{{0x18c3a00, 0xc000036429}}, {0x0, 0x0}})
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:169 +0x137
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/go-cty/cty.transform({0xc000399270, 0x0, 0x16f6d60}, {{{0x18c3a00, 0xc000036429}}, {0x0, 0x0}}, 0xc0006139f8)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/walk.go:181 +0x3fb
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/go-cty/cty.transform({0x0, 0x2e, 0x30}, {{{0x18c3ae0, 0xc00000e0f8}}, {0x16f6d60, 0xc00039d6e0}}, 0xc0001a99f8)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/walk.go:168 +0x594
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/go-cty/cty.Transform(...)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/walk.go:89
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PrepareProviderConfig(0xc00000d440, {0xc00056ef00, 0x17bffce}, 0xc00000e0e0)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:127 +0x166
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PrepareProviderConfig(0xc0002366e0, {0x18c33e0, 0xc00039c1b0}, 0xc00039c1e0)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/terraform-plugin-go@v0.7.0/tfprotov5/tf5server/server.go:524 +0x39e
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PrepareProviderConfig_Handler({0x1796940, 0xc0002366e0}, {0x18c33e0, 0xc00039c1b0}, 0xc00056a060, 0x0)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       github.com/hashicorp/terraform-plugin-go@v0.7.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:259 +0x170
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a0a80, {0x18cfff8, 0xc000314820}, 0xc0002a2000, 0xc00039cd20, 0x1d8c9d8, 0x0)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: google.golang.org/grpc.(*Server).handleStream(0xc0002a0a80, {0x18cfff8, 0xc000314820}, 0xc0002a2000, 0x0)
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: google.golang.org/grpc.(*Server).serveStreams.func1.2()
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       google.golang.org/grpc@v1.44.0/server.go:921 +0x98
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-02-15T12:51:17.176+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.0:       google.golang.org/grpc@v1.44.0/server.go:919 +0x294
2022-02-15T12:51:17.178+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.0/darwin_amd64/terraform-provider-myrasec_v1.21.0 pid=10434 error="exit status 2"
2022-02-15T12:51:17.178+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
╷
│ Error: Plugin did not respond
│ 
│   with provider["registry.terraform.io/myra-security-gmbh/myrasec"],
│   on main.tf line 48, in provider "myrasec":
│   48: provider "myrasec" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateProviderConfig call. The plugin logs may contain more details.
╵
```

**Comment by xellio** [comment]
Thanks for your report! I will have a look on this issue and inform you as soon as I have a solution for this.

**Comment by xellio** [comment]
@daconstenla 
Sorry for this issue - using v1.21.1 should solve this issue. 
Please let me know if this works for you.

**Comment by daconstenla** [comment]
Just tried:
```bash
terraform init -reconfigure -upgrade

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding myra-security-gmbh/myrasec versions matching "~> 1.21"...
- Using previously-installed myra-security-gmbh/myrasec v1.21.1

Terraform has been successfully initialized!
```
and then plan:
```bash

│ Error: Resource instance managed by newer provider version
│ 
│ The current state of myrasec_dns_record.name was created by a newer provider version than is currently selected. Upgrade the myrasec provider to work
│ with this state.
```

I'm trying to get the version from the state right now.

**Comment by daconstenla** [comment]
Rolled back to the previous `tfstate` state on the s3 bucket and yet is failing, could it be a problem on the provider? 🤔

**Comment by daconstenla** [comment]
Maybe I made a rookie mistake, let me double check 🤔 .

Cleaned locally & untracked files using:

```bash
git clean -xdf

Removing .terraform.lock.hcl
Removing .terraform/

# just checked if there are any files with . prefix files
ls -lA .*

-rw-r--r--  1 dconstenla  staff  0 Feb 21 14:39 .test
```

initialised `terraform`:

```bash
terraform init -reconfigure -upgrade

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding myra-security-gmbh/myrasec versions matching "~> 1.21"...
- Installing myra-security-gmbh/myrasec v1.21.1...
- Installed myra-security-gmbh/myrasec v1.21.1 (self-signed, key ID 73FD087144A9D165)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

executed `terraform plan` with `TF_LOG_PROVIDER` debugging flags:

```bash
TF_LOG_PROVIDER=debug terraform plan
2022-02-21T14:41:18.426+0100 [INFO]  provider: configuring client automatic mTLS
2022-02-21T14:41:18.477+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 args=[.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1]
2022-02-21T14:41:18.486+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 pid=62444
2022-02-21T14:41:18.487+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1
2022-02-21T14:41:18.499+0100 [INFO]  provider.terraform-provider-myrasec_v1.21.1: configuring server automatic mTLS: timestamp=2022-02-21T14:41:18.499+0100
2022-02-21T14:41:18.507+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.1: plugin address: address=/var/folders/ss/fk1dkdp97sj444ldlchfn3fw0000gq/T/plugin3408966709 network=unix timestamp=2022-02-21T14:41:18.507+0100
2022-02-21T14:41:18.508+0100 [DEBUG] provider: using plugin: version=5
2022-02-21T14:41:18.549+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-02-21T14:41:18.550+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 pid=62444
2022-02-21T14:41:18.551+0100 [DEBUG] provider: plugin exited
2022-02-21T14:41:18.566+0100 [INFO]  provider: configuring client automatic mTLS
2022-02-21T14:41:18.602+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 args=[.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1]
2022-02-21T14:41:18.611+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 pid=62445
2022-02-21T14:41:18.611+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1
2022-02-21T14:41:18.624+0100 [INFO]  provider.terraform-provider-myrasec_v1.21.1: configuring server automatic mTLS: timestamp=2022-02-21T14:41:18.623+0100
2022-02-21T14:41:18.632+0100 [DEBUG] provider: using plugin: version=5
2022-02-21T14:41:18.632+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.1: plugin address: address=/var/folders/ss/fk1dkdp97sj444ldlchfn3fw0000gq/T/plugin2567902415 network=unix timestamp=2022-02-21T14:41:18.632+0100
2022-02-21T14:41:18.686+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-02-21T14:41:18.688+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 pid=62445
2022-02-21T14:41:18.688+0100 [DEBUG] provider: plugin exited
2022-02-21T14:41:18.693+0100 [INFO]  provider: configuring client automatic mTLS
2022-02-21T14:41:18.731+0100 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 args=[.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1]
2022-02-21T14:41:18.741+0100 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1 pid=62446
2022-02-21T14:41:18.741+0100 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/myra-security-gmbh/myrasec/1.21.1/darwin_amd64/terraform-provider-myrasec_v1.21.1
2022-02-21T14:41:18.753+0100 [INFO]  provider.terraform-provider-myrasec_v1.21.1: configuring server automatic mTLS: timestamp=2022-02-21T14:41:18.753+0100
2022-02-21T14:41:18.762+0100 [DEBUG] provider: using plugin: version=5
2022-02-21T14:41:18.762+0100 [DEBUG] provider.terraform-provider-myrasec_v1.21.1: plugin address: address=/var/folders/ss/fk1dkdp97sj444ldlchfn3fw0000gq/T/plugin898729823 network=unix timestamp=2022-02-21T14:41:18.762+0100

```

yet problem seems to be happening 🤔 

```bash
│ Error: Resource instance managed by newer provider version
│ 
│ The current state of myrasec_dns_record.name was created by a newer provider version than is currently selected. Upgrade the myrasec provider to work
│ with this state.
```

I'm not so sure on how to proceed, I might try to start with a clean slate and see how it goes, maybe we'll need to re-import the existing resources.

Do you support `terraform import` with your provider?

**Comment by xellio** [comment]
`terraform import` is supported, ja - but you have to know about the ID(s) of the elements you want to create. You can fetch them using data sources (for example).

Anyway, I will try to reproduce your problem again.

**Comment by daconstenla** [comment]
If you want / is useful I can pull and share a partial terraform state removing sensitive information from it.

**Comment by xellio** [comment]
I think we improved the provider in a way that this should not happen again. I will close this issue now. In case this or some simlar issue happens again, feel free to open a new issue.
